version: '3.9'

services:
  front:
    build:
      context: .
      dockerfile: docker/svelte-kit/Dockerfile
    ports:
      - 5173:5173
    depends_on:
      auth:
        condition: service_healthy
    volumes:
      - ./front:/home/node/svelte-kit
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: mc-front
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5173/api/healthz || exit 1
      timeout: 30s
      interval: 2s
      retries: 30

  auth:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: mc-auth
    restart: unless-stopped
    environment:
      DATABASE_URL: "${AUTH_DB_URL:?err}"
      USER_API_URL: "${USER_API_URL:?err}"
      ARTICLE_API_URL: "${ARTICLE_API_URL:?err}"
      JAEGER_URL: "${JAEGER_URL:?err}"
      JWT_SECRET: "${JWT_SECRET:?err}"
      PORT: 4000
      insecure: true
    volumes:
      - ./auth-api:/home/node/api
    stdin_open: true
    tty: true
    ports:
      - 4002:4000
    depends_on:
      user:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1
      timeout: 30s
      interval: 2s
      retries: 30

  user:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: mc-user
    restart: unless-stopped
    environment:
      DATABASE_URL: "${USER_DB_URL:?err}"
      AUTH_API_URL: "${AUTH_API_URL:?err}"
      JAEGER_URL: "${JAEGER_URL:?err}"
      JWT_SECRET: "${JWT_SECRET:?err}"
      insecure: true
      PORT: 4000
    volumes:
      - ./user-api:/home/node/api
    stdin_open: true
    tty: true
    ports:
      - 4001:4000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1
      timeout: 30s
      interval: 2s
      retries: 30
  
  article:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: mc-article
    restart: unless-stopped
    environment:
      DATABASE_URL: "${ARTICLE_DB_URL:?err}"
      AUTH_API_URL: "${AUTH_API_URL:?err}"
      JAEGER_URL: "${JAEGER_URL:?err}"
      JWT_SECRET: "${JWT_SECRET:?err}"
      insecure: true
      PORT: 4000
    volumes:
      - ./article-api:/home/node/api
    stdin_open: true
    tty: true
    ports:
      - 4000:4000
    depends_on:
      auth:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1
      timeout: 30s
      interval: 2s
      retries: 30

  tracing:
    image: jaegertracing/all-in-one
    container_name: mc-tracing
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6832:6832/udp
      - 6831:6831/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  # mailer:
  #   build:
  #     context: .
  #     dockerfile: ./docker/node/Dockerfile
  #   container_name: mc-mailer
  #   restart: unless-stopped
  #   volumes:
  #     - ./mailer:/home/node/api
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - 5001:3000
  #   depends_on:
  #     auth:
  #       condition: service_healthy
  #   healthcheck:
  #     test: [ "CMD", "node", "-v" ]
  #     timeout: 30s
  #     interval: 2s
  #     retries: 30

  # mailcatcher:
  #   image: schickling/mailcatcher:latest
  #   ports:
  #     - "1080:1080"
  #   container_name: mc-mailcatcher
  #   depends_on:
  #     mailer:
  #       condition: service_healthy

  db:
    image: mariadb:10.10.2
    restart: unless-stopped
    container_name: mc-db
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD:?err}"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 30s
      interval: 2s
      retries: 30

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    container_name: su-phpmyadmin
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 512M
      MAX_EXECUTION_TIME: 300