// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "article/v1alpha/service.proto" (package "article.v1alpha", syntax proto3)
// tslint:disable
import { UpdateCommentResponse } from "./request";
import { UpdateCommentRequest } from "./request";
import { RemoveCommentResponse } from "./request";
import { RemoveCommentRequest } from "./request";
import { AddCommentResponse } from "./request";
import { AddCommentRequest } from "./request";
import { DeleteArticleResponse } from "./request";
import { DeleteArticleRequest } from "./request";
import { UpdateArticleResponse } from "./request";
import { UpdateArticleRequest } from "./request";
import { CreateArticleResponse } from "./request";
import { CreateArticleRequest } from "./request";
import { GetArticleResponse } from "./request";
import { GetArticleRequest } from "./request";
import { ListArticlesResponse } from "./request";
import { ListArticlesRequest } from "./request";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service article.v1alpha.ArticleService
 */
export const ArticleService = new ServiceType("article.v1alpha.ArticleService", [
    { name: "ListArticles", options: {}, I: ListArticlesRequest, O: ListArticlesResponse },
    { name: "GetArticle", options: {}, I: GetArticleRequest, O: GetArticleResponse },
    { name: "CreateArticle", options: {}, I: CreateArticleRequest, O: CreateArticleResponse },
    { name: "UpdateArticle", options: {}, I: UpdateArticleRequest, O: UpdateArticleResponse },
    { name: "DeleteArticle", options: {}, I: DeleteArticleRequest, O: DeleteArticleResponse }
]);
/**
 * @generated ServiceType for protobuf service article.v1alpha.CommentService
 */
export const CommentService = new ServiceType("article.v1alpha.CommentService", [
    { name: "AddComment", options: {}, I: AddCommentRequest, O: AddCommentResponse },
    { name: "RemoveComment", options: {}, I: RemoveCommentRequest, O: RemoveCommentResponse },
    { name: "UpdateComment", options: {}, I: UpdateCommentRequest, O: UpdateCommentResponse }
]);
